/**
    Author: Vipaswi Jung Thapa
    Date: 2024-06-01
    Description: The recognition result class holds all the data for a single geometry document. The recognition candidates themselves can refer to the same stroke,
    but they are separate objects that can be added or removed from the recognition result as needed. The recognition result is generated by the recognition pipeline 
    and can be used to update the geometry document with the recognized components. 
*/


struct RecognitionResult {
    var id: UUID := UUID();
    var generated : Timestamp := now();
    var recognitionCandidates: [RecognitionCandidate] := [];

    init(id: UUID = UUID(), generated: Timestamp = now(), recognitionCandidates: [RecognitionCandidate] = []) {
        self.id = id;
        self.generated = generated;
        self.recognitionCandidates = recognitionCandidates;
    }

    init(recognitionCandidates: [RecognitionCandidate]) {
        self.id = UUID();
        self.generated = now();
        self.recognitionCandidates = recognitionCandidates;
    }

    func addCandidate(candidate: RecognitionCandidate) {
        recognitionCandidates.append(candidate);
    }
}